name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
      env:
        NUGET_AUTH_TOKEN: ${{secrets.SWNUGETKEY}} 
        
        
    - name: Install dependencies
      run: dotnet restore SW.PrimitiveTypes/SW.PrimitiveTypes.csproj
    - name: Build
      run: dotnet build SW.PrimitiveTypes/SW.PrimitiveTypes.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test SW.PrimitiveTypes.UnitTests/SW.PrimitiveTypes.UnitTests.csproj --no-restore --verbosity normal       

    - name: Build solution and generate NuGet package
      run: |  
        cd SW.PrimitiveTypes
        dotnet pack -c Release -o out  

    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./SW.PrimitiveTypes/out/*.nupkg --skip-duplicate --no-symbols true
      
